name: Build Argilla server docker image

on:
  workflow_call:
    inputs:
      is_release:
        description: "True if the image is a release"
        required: true
        type: boolean

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    env:
      PLATFORMS: "linux/amd64"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: argilla-server/pyproject.toml
          cache-dependency-path: argilla-server/pdm.lock
          cache: true

      - name: Setup ARM platforms
        if: ${{ inputs.is_release }}
        run: |
          echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ inputs.is_release }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read package info
        id: package-info
        working-directory: argilla-server
        run: |
          PACKAGE_VERSION=$(pdm show --version)
          PACKAGE_NAME=$(pdm show --name)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "$PACKAGE_NAME==$PACKAGE_VERSION"

      - name: Download python package
        uses: actions/download-artifact@v4
        with:
          name: argilla-server
          path: argilla-server/docker/server/dist

      - name: Get Docker image tag from GITHUB_REF
        id: docker-image-tag-from-ref
        uses: ./.github/actions/docker-image-tag-from-ref

      - name: Set image tag from GITHUB_REF
        run: |
          echo "IMAGE_TAG=${{ steps.docker-image-tag-from-ref.outputs.docker-image-tag }}" >> $GITHUB_ENV

      - name: Set image tag from package version
        if: ${{ inputs.is_release }}
        run: |
          echo "IMAGE_TAG=${{ steps.package-info.outputs.PACKAGE_VERSION }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AR_DOCKER_USERNAME }}
          password: ${{ secrets.AR_DOCKER_PASSWORD }}

      - name: Build and push `argilla-server` image
        uses: docker/build-push-action@v5
        with:
          context: argilla-server/docker/server
          file: argilla-server/docker/server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: argilla/argilla-server:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Push latest `argilla-server` image
        if: ${{ inputs.is_release }}
        uses: docker/build-push-action@v5
        with:
          context: argilla-server/docker/server
          file: argilla-server/docker/server/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: argilla/argilla-server:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Push latest `argilla-quickstart` image
        if: ${{ inputs.is_release }}
        uses: docker/build-push-action@v5
        with:
          context: argilla-server/docker/quickstart
          file: argilla-server/docker/quickstart/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: argilla/argilla-quickstart:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARGILLA_VERSION=${{ env.IMAGE_TAG }}
          push: true

      - name: Push latest `argilla-quickstart` image
        if: ${{ inputs.is_release }}
        uses: docker/build-push-action@v5
        with:
          context: argilla-server/docker/quickstart
          file: argilla-server/docker/quickstart/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: argilla/argilla-quickstart:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARGILLA_VERSION=${{ env.IMAGE_TAG }}
          push: true

      - name: Docker Hub Description for `argilla-server`
        uses: peter-evans/dockerhub-description@v4
        if: ${{ inputs.is_release }}
        with:
          username: ${{ secrets.AR_DOCKER_USERNAME }}
          password: ${{ secrets.AR_DOCKER_PASSWORD }}
          repository: ${{ inputs.image-name }}
          readme-filepath: ${{ inputs.readme }}

      - name: Docker Hub Description for `argilla-quickstart`
        uses: peter-evans/dockerhub-description@v4
        if: ${{ inputs.is_release }}
        with:
          username: ${{ secrets.AR_DOCKER_USERNAME }}
          password: ${{ secrets.AR_DOCKER_PASSWORD }}
          repository: ${{ inputs.image-name }}
          readme-filepath: ${{ inputs.readme }}
